apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager-rest
  namespace: flink
spec:
  type: NodePort
  ports:
    - name: rest
      port: 8081
      targetPort: 8081
  selector:
    app: flink
    component: jobmanager
---
apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager-rpc
  namespace: flink
spec:
  type: NodePort
  ports:
    - name: rpc
      port: 6123
      targetPort: 6123
  selector:
    app: flink
    component: jobmanager